<?php

namespace  Drupal\mod_block\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

class MBAdminForm extends ConfigFormBase{
    /**
     * Returns a unique string identifying the form.
     *
     * @return string
     *   The unique string identifying the form.
     */
    public function getFormId()
    {
        return 'mod_block_admin_settings';
    }

    /**
     * Gets the configuration names that will be editable.
     *
     * @return array
     *   An array of configuration object names that are editable if called in
     *   conjunction with the trait's config() method.
     */
    protected function getEditableConfigNames()
    {
        return array('mod_block.settings');
    }


    /**
     * {@inheritdoc}
     */
    public function buildForm(array $form, FormStateInterface $form_state)
    {
        $config = $this->config('mod_block.settings');
        $form['mod_block_animation_pages_init_action'] = array(
            '#type' => 'radios',
            '#title' => t('Enable animate on specific pages '),
            '#options' => array(
                'page_enable' => t('Load only on the listed pages.'),
                'page_disable' => t('Load on every page except the listed pages.')
            ),
            '#default_value' => $config->get('mod_block_animation_pages_init_action') ? $config->get('mod_block_animation_pages_init_action') : 'page_enable',
        );
        $form['mod_block_animation_pages_list'] = array(
            '#type' => 'textarea',
            '#title' => t('Pages'),
            '#description' => t('List one page per line as Drupal paths.  The * character is a wildcard.  Example paths are "node/add/page" and "node/add/*".  Use <front> to match the front page.'),
            '#default_value' => $config->get('mod_block_animation_pages_list') ? $config->get('mod_block_animation_pages_list') : '' //variable_get('mod_block_animation_pages_list','')
        );
        /*
        $form['mod_block_animation_mobile'] = array(
            '#type' => 'checkbox',
            '#title' => t('Disable animate on mobile'),
            '#default_value' => $config->get('mod_block_animation_mobile') ? $config->get('mod_block_animation_mobile') : 0//variable_get('mod_block_animation_mobile', 0),
        );
        */

        return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function submitForm(array &$form, FormStateInterface $form_state)
    {
        $values = $form_state->getValues();

        $this->config('mod_block.settings')
            ->set('mod_block_animation_pages_init_action',$values['mod_block_animation_pages_init_action'])
            ->set('mod_block_animation_pages_list',$values['mod_block_animation_pages_list'])
            /*->set('mod_block_animation_mobile',$values['mod_block_animation_mobile'])*/
            ->save();

        parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
    }


}